name: ESPHome Publish

on:
  push:
    paths:
      - esphome/**/*.yaml
    branches:
      - main
  workflow_dispatch:

jobs:
  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build Firmware
        uses: esphome/build-action@v7
        id: esphome-build
        with:
          yaml-file: esphome/metro-display.factory.yaml
          complete-manifest: true
          cache: true
      - name: Move files for versioning
        run: |
          mkdir -p esphome/firmware
          mkdir -p esphome/firmware/${{ steps.esphome-build.outputs.project-version }}
          cp ${{ steps.esphome-build.outputs.name }}/${{ steps.esphome-build.outputs.name }}.factory.bin esphome/firmware/${{ steps.esphome-build.outputs.name }}.factory.bin
          mv ${{ steps.esphome-build.outputs.name }}/${{ steps.esphome-build.outputs.name }}.factory.bin esphome/firmware/${{ steps.esphome-build.outputs.project-version }}/${{ steps.esphome-build.outputs.name }}.factory.bin
          cp ${{ steps.esphome-build.outputs.name }}/${{ steps.esphome-build.outputs.name }}.ota.bin esphome/firmware/${{ steps.esphome-build.outputs.name }}.ota.bin
          mv ${{ steps.esphome-build.outputs.name }}/${{ steps.esphome-build.outputs.name }}.ota.bin esphome/firmware/${{ steps.esphome-build.outputs.project-version }}/${{ steps.esphome-build.outputs.name }}.ota.bin
          cp ${{ steps.esphome-build.outputs.name }}/manifest.json esphome/firmware/manifest.json
          mv ${{ steps.esphome-build.outputs.name }}/manifest.json esphome/firmware/${{ steps.esphome-build.outputs.project-version }}/manifest.json
          rm -rf ${{ steps.esphome-build.outputs.name }}/
      - name: Commit firmware to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ESPHome Firmware ${{ steps.esphome-build.outputs.project-version }} release
          tagging_message: esphome-${{ steps.esphome-build.outputs.project-version }}
